

services:
  postgres:
    image: postgres:15-alpine
    container_name: queuehive-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Joseph123
      POSTGRES_DB: queuehive_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d queuehive_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  queuehive-backend:
    build: .
    container_name: queuehive-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      postgres:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    container_name: queuehive-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@queuehive.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
